pipeline {
    agent any

    stages {
                stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r flaskapp/requirements.txt
                '''
            }
        }
        

        stage('Run Tests') {
            steps {
                sh 'chmod +x ci/run_tests.sh && ./ci/run_tests.sh'
            }
        }

        stage('Archive Results') {
            steps {
                archiveArtifacts artifacts: 'results.json', fingerprint: true
            }
        }
    }

    post {
        success {
            echo '✅ Build and tests passed!'
        }
        failure {
            echo '❌ Build or tests failed!'
        }
    }
}
